---
- name: Update servers
  hosts: all
  remote_user: ladmin
  become: true

  pre_tasks:
    - name: Wait for cloud init to finish
      community.general.cloud_init_data_facts:
        filter: status
      register: res
      until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
      retries: 60
      delay: 5

  roles:
    - { role: packages }
    - { role: autoupdate }
    #- { role: firewall }
    #- { role: cockpit }
