---
- block:
    - name: Install dnf-automatic
      ansible.builtin.dnf:
        name: dnf-automatic
        state: present
        update_cache: true

    - name: Enable/start dnf-automatic
      ansible.builtin.systemd:
        name: dnf-automatic.timer
        state: started
        enabled: true

    - name: Configure dnf-automatic
      community.general.ini_file:
        path: /etc/dnf/automatic.conf
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        mode: "0644"
      loop: "{{ automatic_conf }}"
      notify:
        - Restart dnf-automatic
